// <auto-generated />
using System;
using EbedrendeloApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EbedrendeloApp.Data.Migrations
{
    [DbContext(typeof(EbedrendeloDbContext))]
    [Migration("20260824102023_AddMenuDishNutrition")]
    partial class AddMenuDishNutrition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteDailyOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ALaCarteItemId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OrderedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ALaCarteItemId");

                    b.HasIndex("Date", "ALaCarteItemId")
                        .IsUnique();

                    b.ToTable("ALaCarteDailyOffers");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PriceHuf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ALaCarteItems");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OrderingPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlacedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("TotalHuf")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderingPeriodId");

                    b.HasIndex("PlacedByUserId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("ALaCarteOrders");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ALaCarteDailyOfferId")
                        .HasColumnType("int");

                    b.Property<int>("ALaCarteOrderId")
                        .HasColumnType("int");

                    b.Property<int>("CategorySnapshot")
                        .HasColumnType("int");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UnitPriceHuf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ALaCarteDailyOfferId");

                    b.HasIndex("ALaCarteOrderId", "ALaCarteDailyOfferId")
                        .IsUnique();

                    b.ToTable("ALaCarteOrderLines");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ALaCarteOrderDeadlineLocalTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ChangeDeadlineLocalTime")
                        .HasColumnType("time");

                    b.Property<int>("ChangeDeadlineWorkingDays")
                        .HasColumnType("int");

                    b.Property<int>("MenuPortionHuf")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.CreditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountHuf")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumesCreditEntryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PeriodInvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingHuf")
                        .HasColumnType("int");

                    b.Property<int?>("SourceMenuOrderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumesCreditEntryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PeriodInvoiceId");

                    b.HasIndex("SourceMenuOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("CreditEntries");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.DailyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyMenus");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ExcludedDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ExcludedDays");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.KitchenClosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TotalPortions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("KitchenClosures");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.KitchenClosureLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KitchenClosureId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("VariantNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("KitchenClosureId");

                    b.ToTable("KitchenClosureLines");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.MenuDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("CarbohydrateGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("EnergyKcal")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("FatGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("ProteinGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("SaltGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("SaturatedFatGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("SugarGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Name")
                        .IsUnique();

                    b.ToTable("MenuDishes");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.MenuOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledByExcludedDayId")
                        .HasColumnType("int");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MenuVariantId")
                        .HasColumnType("int");

                    b.Property<int>("OrderingPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlacedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PriceHuf")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReassignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReassignedFromVariantCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByExcludedDayId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("MenuVariantId");

                    b.HasIndex("PlacedByUserId");

                    b.HasIndex("Date", "Status");

                    b.HasIndex("OrderingPeriodId", "UserId");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("MenuOrders");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.MenuVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("DailyMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId", "Code")
                        .IsUnique();

                    b.ToTable("MenuVariants");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.OrderingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OrderDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .IsUnique();

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("OrderingPeriods");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.PeriodInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ALaCarteGrossHuf")
                        .HasColumnType("int");

                    b.Property<int>("ALaCartePayableHuf")
                        .HasColumnType("int");

                    b.Property<int>("CreditAppliedHuf")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrossHuf")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("MarkedPaidByUserId")
                        .HasColumnType("int");

                    b.Property<int>("MenuGrossHuf")
                        .HasColumnType("int");

                    b.Property<int>("MenuPayableHuf")
                        .HasColumnType("int");

                    b.Property<int>("OrderingPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayableHuf")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkedPaidByUserId");

                    b.HasIndex("OrderingPeriodId");

                    b.HasIndex("UserId", "OrderingPeriodId")
                        .IsUnique();

                    b.ToTable("PeriodInvoices");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KeresztNev")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Rf")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SzervKod")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("VezetekNev")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("RelatedDate")
                        .HasColumnType("date");

                    b.Property<int?>("RelatedMenuOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMenuOrderId");

                    b.HasIndex("UserId", "ReadAtUtc", "CreatedAtUtc");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteDailyOffer", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.ALaCarteItem", "ALaCarteItem")
                        .WithMany()
                        .HasForeignKey("ALaCarteItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ALaCarteItem");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteOrder", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.OrderingPeriod", null)
                        .WithMany()
                        .HasForeignKey("OrderingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlacedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteOrderLine", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.ALaCarteDailyOffer", null)
                        .WithMany()
                        .HasForeignKey("ALaCarteDailyOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.ALaCarteOrder", "ALaCarteOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ALaCarteOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ALaCarteOrder");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.AppSetting", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.CreditEntry", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.CreditEntry", null)
                        .WithMany()
                        .HasForeignKey("ConsumesCreditEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.PeriodInvoice", null)
                        .WithMany()
                        .HasForeignKey("PeriodInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.MenuOrder", null)
                        .WithMany()
                        .HasForeignKey("SourceMenuOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ExcludedDay", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.KitchenClosure", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.KitchenClosureLine", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.KitchenClosure", "KitchenClosure")
                        .WithMany("Lines")
                        .HasForeignKey("KitchenClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KitchenClosure");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.MenuOrder", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.ExcludedDay", null)
                        .WithMany()
                        .HasForeignKey("CancelledByExcludedDayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.MenuVariant", null)
                        .WithMany()
                        .HasForeignKey("MenuVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.OrderingPeriod", null)
                        .WithMany()
                        .HasForeignKey("OrderingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PlacedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.MenuVariant", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.DailyMenu", "DailyMenu")
                        .WithMany("Variants")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMenu");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.PeriodInvoice", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MarkedPaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.OrderingPeriod", null)
                        .WithMany()
                        .HasForeignKey("OrderingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.User", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("EbedrendeloApp.Domain.Entities.MenuOrder", null)
                        .WithMany()
                        .HasForeignKey("RelatedMenuOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EbedrendeloApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.ALaCarteOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.DailyMenu", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("EbedrendeloApp.Domain.Entities.KitchenClosure", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
